# Generated by Django 5.2 on 2025-06-23 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_type', models.CharField(choices=[('USD', 'Dollars'), ('INR', 'Rupees'), ('EUR', 'Euros'), ('GBP', 'Pounds'), ('JPY', 'Yen'), ('CNY', 'Yuan'), ('CAD', 'Canadian Dollars'), ('AUD', 'Australian Dollars')], default='USD', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='core.user')),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.account'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='core.account'),
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
